In [1]:
import torchmetrics
import torch
import torch.nn.functional as F

from einops import rearrange

In [1]:
import torchmetrics
import torch

# multiclass with logits
# (N, C), N=3, C=3
preds = torch.tensor([[0.2, 0.8, 0.0], 
                      [0.1, 0.2, 0.7],
                      [0.1, 0.8, 0.1]], 
                      dtype=torch.float16)
target = torch.tensor([1, 0, 0])


torchmetrics.functional.classification.multiclass_accuracy(
    preds, target, 
    num_classes=3,
    ignore_index=-1,
    average='none',
    top_k=1)

tensor([0., 1., 0.])

In [2]:
torchmetrics.__version__

'0.9.3'

In [29]:
# multidimensional, multiclass with logits
# 2 samples, 3 classes, each sample is of length 2
preds = torch.tensor([[[0.2, 0.7, 0.1], [0.1, 0.5, 0.4]], 
                      [[0.8, 0.1, 0.1], [0.2, 0.1, 0.7]]],
                      dtype=torch.float)
preds = rearrange(preds, 'n s c -> n c s')

target = torch.tensor([[1, 1], 
                       [0, 0]], dtype=torch.long)

f'{preds.shape=}'
f'{target.shape=}'

# torchmetrics.functional.classification.multiclass_accuracy(
#     preds, target, num_classes=3, 
#     multidim_average='samplewise', average='micro', 
#     ignore_index=-100)
torch.nn.CrossEntropyLoss(ignore_index=-100, reduction='mean')(preds, target)
# torch.nn.CrossEntropyLoss(ignore_index=-100, reduction='mean')(preds, target)

preds = F.log_softmax(preds, dim=1)
F.nll_loss(preds, target, reduction='mean', ignore_index=-100)

'preds.shape=torch.Size([2, 3, 2])'

'target.shape=torch.Size([2, 2])'

tensor(0.9179)

tensor(0.9179)

In [53]:
# multi-label, multi-class
preds = torch.tensor([[0.2, 0.8, 0.6], 
                      [0.1, 0.8, 0.6],
                      [0.1, 0.8, 0.6]])

target = torch.tensor([[1., 1, 1],
                       [1, 1, 1], 
                       [1, 1, 1]])

torchmetrics.functional.classification.multilabel_accuracy(
    preds, target,
    threshold=0.5,
    num_labels=3,
    ignore_index=-100,
    average='none')

torchmetrics.functional.classification.multilabel_accuracy(
    preds, target,
    threshold=0.5,
    num_labels=3,
    ignore_index=-100,
    average='micro')

# torch.nn.functional.sigmoid(preds)
# torch.nn.functional.logsigmoid(preds)
torch.nn.functional.binary_cross_entropy_with_logits(preds, target, reduction='none')

x = torch.nn.functional.sigmoid(preds)
torch.nn.functional.binary_cross_entropy(x, target, reduction='none')

tensor([0., 1., 1.])

tensor(0.6667)

tensor([[0.5981, 0.3711, 0.4375],
        [0.6444, 0.3711, 0.4375],
        [0.6444, 0.3711, 0.4375]])

tensor([[0.5981, 0.3711, 0.4375],
        [0.6444, 0.3711, 0.4375],
        [0.6444, 0.3711, 0.4375]])

In [35]:
torch.log(torch.tensor(1-0.5498))

tensor(-0.7981)

In [23]:
from torch import nn

target = torch.ones([10, 64], dtype=torch.float32)  # 64 classes, batch size = 10
output = torch.full([10, 64], 1.5)  # A prediction (logit)
output.shape
target.shape
pos_weight = torch.ones([64])  # All weights are equal to 1
criterion = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)
criterion(output, target)  # -log(sigmoid(1.5))

torch.Size([10, 64])

torch.Size([10, 64])

tensor(0.2014)

In [1]:
import sys

#Spark ML and SQL
from pyspark.ml import Pipeline, PipelineModel
from pyspark.sql.functions import array_contains
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType
#Spark NLP
import sparknlp
from sparknlp.pretrained import PretrainedPipeline
from sparknlp.annotator import *
from sparknlp.common import RegexRule
from sparknlp.base import DocumentAssembler, Finisher

In [2]:
spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)

:: loading settings :: url = jar:file:/home/yu/OneDrive/App/python/python-env/py39-base/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml


Ivy Default Cache set to: /home/yu/.ivy2/cache
The jars for the packages stored in: /home/yu/.ivy2/jars
com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-8fa0966f-38f2-4ad0-896a-847931def654;1.0
	confs: [default]
	found com.johnsnowlabs.nlp#spark-nlp_2.12;4.1.0 in central
	found com.typesafe#config;1.4.2 in central
	found org.rocksdb#rocksdbjni;6.29.5 in central
	found com.amazonaws#aws-java-sdk-bundle;1.11.828 in central
	found com.github.universal-automata#liblevenshtein;3.0.0 in central
	found com.google.code.findbugs#annotations;3.0.1 in central
	found net.jcip#jcip-annotations;1.0 in central
	found com.google.code.findbugs#jsr305;3.0.1 in central
	found com.google.protobuf#protobuf-java-util;3.0.0-beta-3 in central
	found com.google.protobuf#protobuf-java;3.0.0-beta-3 in central
	found com.google.code.gson#gson;2.3 in central
	found it.unimi.dsi#fastutil;7.0.12 in central
	found org.projectlombok#lombok;1.16

22/09/26 14:55:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).


22/09/26 14:55:29 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Spark NLP version:  4.1.0
Apache Spark version:  3.3.0


In [3]:
pipeline = PretrainedPipeline('match_datetime', lang='en')

match_datetime download started this may take some time.
Approx size to download 9.7 KB
[ | ]match_datetime download started this may take some time.
Approximate size to download 9.7 KB
[ / ]Download done! Loading the resource.
[OK!]


In [9]:
from sutime import SUTime
sutime = SUTime(mark_time_ranges=True,
                include_range=True, language='english')

[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator sutime with class edu.stanford.nlp.time.TimeAnnotator
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator sutime
